name: Deploy All Files from GitHub 'trunk' to WordPress Plugin SVN

on:
  push:
    branches:
      - sagar  # Change this to the branch you want to deploy from (e.g., 'main')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub repository
      uses: actions/checkout@v3

    - name: Set up SVN (subversion package)
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion  # Install subversion instead of svn

    - name: Checkout WordPress Plugin SVN
      run: |
        svn co https://plugins.svn.wordpress.org/in-this-article/trunk/ trunk

    - name: Copy files from GitHub 'trunk' to SVN 'trunk'
      run: |
        # Copy all files from the GitHub 'trunk' folder to SVN 'trunk' folder
        rsync -av --exclude .git ./trunk/ ./trunk/

    - name: Commit and push changes to SVN
      run: |
        cd trunk
        svn add * --force  # Add all files (including new files and directories)
        svn commit -m "Deploying all files from GitHub 'trunk' to WordPress plugin" --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
