name: Update WP Plugin SVN and Create Tag

on:
  release:
    types: [created]  # Trigger the workflow when a new release (tag) is created

jobs:
  update-svn:
    runs-on: ubuntu-latest

    steps:
      # Checkout the GitHub repository (this includes your plugin's files)
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      # Set up SVN on the runner
      - name: Set up SVN
        run: |
          sudo apt-get install -y subversion

      # Configure SVN credentials
      - name: Configure SVN credentials
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          svn --username $SVN_USERNAME --password $SVN_PASSWORD --non-interactive info

      # Checkout the SVN repository
      - name: Checkout SVN repository
        run: |
          svn checkout https://plugins.svn.wordpress.org/in-this-article/trunk plugin-repo

      # Update the plugin files in SVN (if needed)
      - name: Update plugin in SVN
        run: |
          # Add your plugin update steps here (like copying files)
          svn add . --force
          svn commit -m "Update plugin files for release ${{ github.ref_name }}"

      # Create the SVN tag based on the GitHub release tag
      - name: Create SVN tag
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          TAG_NAME=${{ github.ref_name }}  # Use the release tag as the SVN tag name
          svn copy https://plugins.svn.wordpress.org/in-this-article/trunk https://plugins.svn.wordpress.org/in-this-article/tags/$TAG_NAME -m "Tagging version $TAG_NAME"
