name: Deploy to SVN

on:
  push:
    branches:
      - sagar  # You can change this to your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Set up SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Checkout the SVN repository (trunk)
        run: |
          # Checkout the SVN trunk directory into the local working directory
          svn co https://plugins.svn.wordpress.org/in-this-article/ trunk --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
      - name: Remove incorrectly copied files from SVN
        run: |
          # Delete any files outside the 'trunk' folder (you can specify paths here)
          svn delete ./in-this-article.php  # Adjust the file paths if needed
      - name: Copy files from GitHub trunk to SVN trunk
        run: |
          # Copy the contents of the GitHub trunk folder into the SVN trunk directory
          cp -r ./* ./trunk/

      - name: Check SVN status (ensure only modified/new files are added)
        run: |
          cd trunk
          svn status

      - name: Add new/modified files and commit to SVN
        run: |
          cd trunk
          # Add new files to SVN, commit the changes
          svn add --force .
          svn commit -m "Automated commit from GitHub Actions" --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
