name: Deploy Plugin from GitHub to SVN 'trunk' Directory

on:
  push:
    branches:
      - sagar  # Trigger this action on push to the main branch (or your target branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub repository
      uses: actions/checkout@v3

    - name: Set up SVN (subversion package)
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion  # Install subversion package

    - name: Checkout WordPress Plugin SVN 'trunk' Directory
      run: |
        svn co https://plugins.svn.wordpress.org/in-this-article/ trunk  # Checkout the SVN repo

    - name: Update SVN Working Copy
      run: |
        svn update trunk  # Ensure the SVN working copy is up to date

    - name: Copy root plugin folder from GitHub to SVN 'trunk'
      run: |
        rsync -av --exclude .git ./ ./trunk/  # Copy all root plugin files from GitHub to SVN trunk folder (excluding .git)

    - name: Add New/Modified Files to SVN
      run: |
        cd trunk
        svn add * --force  # Add any new or modified files to SVN

    - name: Commit and push changes to SVN
      run: |
        cd trunk
        svn commit -m "Deploying plugin from GitHub to SVN 'trunk' directory" --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
