name: Deploy to WordPress SVN

on:
  push:
    tags:
      - '*'  # Runs on any tag creation

jobs:
  deploy:
    name: Deploy Plugin to WordPress SVN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SVN
        run: sudo apt-get install -y subversion

      - name: Define Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout WordPress SVN Repo
        run: |
          svn co https://plugins.svn.wordpress.org/in-this-article svn-repo

      - name: Copy Plugin Files to Trunk
        run: |
          rsync -av --delete --exclude=".git" --exclude=".github" --exclude=".gitignore" ./ svn-repo/trunk/

      - name: Commit Changes to Trunk
        run: |
          cd svn-repo
          svn add --force trunk/
          svn commit -m "Update trunk to version $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache

      - name: Create New Tag
        run: |
          cd svn-repo
          svn cp trunk tags/$VERSION
          svn commit -m "Tagging version $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache

    env:
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
