name: Deploy to SVN

on:
  push:
    branches:
      - sagar  # You can change this to your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Set up SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Checkout the SVN repository (trunk)
        run: |
          # Checkout the SVN trunk directory into the local working directory
          svn checkout https://plugins.svn.wordpress.org/in-this-article/ --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}

      - name: Copy GitHub files into the SVN trunk
        run: |
          # Now we copy the files from the GitHub repository (current directory) into the SVN 'trunk' directory
          cp -r ./trunk/

      - name: Commit and Push Changes to SVN
        run: |
          cd trunk
          svn add --force .
          svn commit -m "Automated commit from GitHub Actions" --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
