name: Deploy All Files from GitHub 'trunk' to WordPress Plugin SVN

on:
  push:
    branches:
      - sagar  # Trigger this action on push to the main branch (or your target branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub repository
      uses: actions/checkout@v3

    - name: Set up SVN (subversion package)
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion  # Install subversion package

    - name: Checkout WordPress Plugin SVN 'trunk'
      run: |
        svn co https://plugins.svn.wordpress.org/in-this-article/ trunk  # Checkout the SVN repo

    - name: Copy files from GitHub 'trunk' to SVN 'trunk'
      run: |
        cp -r ./trunk/* ./trunk/  # Copy all files from GitHub trunk to SVN trunk

    - name: Commit and push changes to SVN
      run: |
        cd trunk
        svn add * --force  # Add new and modified files to SVN
        svn commit -m "Deploying all files from GitHub 'trunk' to WordPress plugin" --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
