name: Deploy to WordPress SVN

on:
  push:
    tags:
      - '*'  # Runs on any tag creation

jobs:
  deploy:
    name: Deploy Plugin to WordPress SVN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SVN
        run: sudo apt-get install -y subversion

      - name: Define Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout WordPress SVN Repository (Fresh)
        run: |
          rm -rf /tmp/wordpress-svn
          svn checkout https://plugins.svn.wordpress.org/in-this-article /tmp/wordpress-svn --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache --quiet

      - name: Sync Plugin Files to Trunk
        run: |
          rsync -av --delete --exclude=".git" --exclude=".github" --exclude=".gitignore" ./ /tmp/wordpress-svn/trunk/
          cd /tmp/wordpress-svn
          svn status | grep '^!' | awk '{print $2}' | xargs svn delete || true
          svn add --force trunk/

      - name: Commit Changes to Trunk
        run: |
          cd /tmp/wordpress-svn
          svn commit -m "Updating trunk to version $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache

      - name: Create New Tag (After Trunk is Committed)
        run: |
          cd /tmp/wordpress-svn
          svn copy trunk tags/$VERSION
          svn commit -m "Tagging version $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache

    env:
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
