name: Sync to WordPress SVN on Release

on:
  release:
    types:
      - created  # Trigger this workflow when a new release is created

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up SVN
        run: |
          sudo apt-get install subversion

      - name: Sync to SVN
        env:
          SVN_USER: ${{ secrets.SVN_USER }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_URL: https://plugins.svn.wordpress.org/in-this-article  # Your plugin's SVN URL
        run: |
          # Checkout the SVN repository's trunk and tags folders directly
          svn checkout $SVN_URL/trunk trunk

          # Copy GitHub repo files into the trunk folder
          cp -r * trunk/

          # Add new files to SVN (if they are new or modified)
          svn add --force trunk/*

          # Commit changes to SVN's trunk
          svn commit -m "Sync from GitHub: Update plugin to version ${{ github.event.release.tag_name }}" --username $SVN_USER --password $SVN_PASSWORD

          # Tag the release in SVN
          VERSION="${{ github.event.release.tag_name }}"
          svn copy trunk "tags/$VERSION" -m "Tagging release $VERSION" --username $SVN_USER --password $SVN_PASSWORD
